spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlin_api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: apiuser
    password: apipassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: WARN
    com.example.api: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN 