spring:
  datasource:
    url: ${JAWSDB_URL}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.example.api: INFO 